
// This file has been generated by the GUI designer. Do not modify.
namespace DatabaseApplication
{
	public partial class ViewPharmacistWindow
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.HBox hbox5;
		private global::Gtk.Entry sin_entry;
		private global::Gtk.Entry name_entry;
		private global::Gtk.Entry add_entry;
		private global::Gtk.Button button5;
		private global::Gtk.HBox hbox6;
		private global::Gtk.Label label7;
		private global::Gtk.Label label8;
		private global::Gtk.Label label9;
		private global::Gtk.HBox hbox7;
		private global::Gtk.Entry email_entry;
		private global::Gtk.Entry phone_entry;
		private global::Gtk.Entry sal_entry;
		private global::Gtk.Entry super_entry;
		private global::Gtk.Calendar dob_cal;
		private global::Gtk.HBox hbox8;
		private global::Gtk.Label label10;
		private global::Gtk.Label label11;
		private global::Gtk.Label label12;
		private global::Gtk.Label label13;
		private global::Gtk.Label label14;
		private global::Gtk.Button button2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DatabaseApplication.ViewPharmacistWindow
			this.Name = "DatabaseApplication.ViewPharmacistWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("ViewPharmacistWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child DatabaseApplication.ViewPharmacistWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.sin_entry = new global::Gtk.Entry ();
			this.sin_entry.CanFocus = true;
			this.sin_entry.Name = "sin_entry";
			this.sin_entry.IsEditable = false;
			this.sin_entry.InvisibleChar = '●';
			this.hbox5.Add (this.sin_entry);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.sin_entry]));
			w1.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.name_entry = new global::Gtk.Entry ();
			this.name_entry.CanFocus = true;
			this.name_entry.Name = "name_entry";
			this.name_entry.IsEditable = true;
			this.name_entry.InvisibleChar = '●';
			this.hbox5.Add (this.name_entry);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.name_entry]));
			w2.Position = 1;
			// Container child hbox5.Gtk.Box+BoxChild
			this.add_entry = new global::Gtk.Entry ();
			this.add_entry.CanFocus = true;
			this.add_entry.Name = "add_entry";
			this.add_entry.IsEditable = true;
			this.add_entry.InvisibleChar = '●';
			this.hbox5.Add (this.add_entry);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.add_entry]));
			w3.Position = 2;
			// Container child hbox5.Gtk.Box+BoxChild
			this.button5 = new global::Gtk.Button ();
			this.button5.CanFocus = true;
			this.button5.Name = "button5";
			this.button5.UseUnderline = true;
			this.button5.Label = global::Mono.Unix.Catalog.GetString ("Delete Pharmacist");
			this.hbox5.Add (this.button5);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.button5]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox2.Add (this.hbox5);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox5]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Social Insurance Number");
			this.hbox6.Add (this.label7);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label7]));
			w6.Position = 0;
			w6.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Name");
			this.hbox6.Add (this.label8);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label8]));
			w7.Position = 1;
			w7.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Address");
			this.hbox6.Add (this.label9);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label9]));
			w8.Position = 2;
			w8.Fill = false;
			this.vbox2.Add (this.hbox6);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox6]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.email_entry = new global::Gtk.Entry ();
			this.email_entry.CanFocus = true;
			this.email_entry.Name = "email_entry";
			this.email_entry.IsEditable = true;
			this.email_entry.InvisibleChar = '●';
			this.hbox7.Add (this.email_entry);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.email_entry]));
			w10.Position = 0;
			// Container child hbox7.Gtk.Box+BoxChild
			this.phone_entry = new global::Gtk.Entry ();
			this.phone_entry.CanFocus = true;
			this.phone_entry.Name = "phone_entry";
			this.phone_entry.IsEditable = true;
			this.phone_entry.InvisibleChar = '●';
			this.hbox7.Add (this.phone_entry);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.phone_entry]));
			w11.Position = 1;
			// Container child hbox7.Gtk.Box+BoxChild
			this.sal_entry = new global::Gtk.Entry ();
			this.sal_entry.CanFocus = true;
			this.sal_entry.Name = "sal_entry";
			this.sal_entry.IsEditable = true;
			this.sal_entry.InvisibleChar = '●';
			this.hbox7.Add (this.sal_entry);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.sal_entry]));
			w12.Position = 2;
			// Container child hbox7.Gtk.Box+BoxChild
			this.super_entry = new global::Gtk.Entry ();
			this.super_entry.CanFocus = true;
			this.super_entry.Name = "super_entry";
			this.super_entry.IsEditable = false;
			this.super_entry.InvisibleChar = '●';
			this.hbox7.Add (this.super_entry);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.super_entry]));
			w13.Position = 3;
			// Container child hbox7.Gtk.Box+BoxChild
			this.dob_cal = new global::Gtk.Calendar ();
			this.dob_cal.CanFocus = true;
			this.dob_cal.Name = "dob_cal";
			this.dob_cal.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.hbox7.Add (this.dob_cal);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.dob_cal]));
			w14.Position = 4;
			w14.Expand = false;
			w14.Fill = false;
			this.vbox2.Add (this.hbox7);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox7]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Email");
			this.hbox8.Add (this.label10);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label10]));
			w16.Position = 0;
			w16.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Phone");
			this.hbox8.Add (this.label11);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label11]));
			w17.Position = 1;
			w17.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Salary");
			this.hbox8.Add (this.label12);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label12]));
			w18.Position = 2;
			w18.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Supervisor (SIN)");
			this.hbox8.Add (this.label13);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label13]));
			w19.Position = 3;
			w19.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Date of Birth");
			this.hbox8.Add (this.label14);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label14]));
			w20.Position = 4;
			w20.Fill = false;
			this.vbox2.Add (this.hbox8);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox8]));
			w21.Position = 3;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.button2 = new global::Gtk.Button ();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = global::Mono.Unix.Catalog.GetString ("Update Pharmacist");
			this.vbox2.Add (this.button2);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button2]));
			w22.PackType = ((global::Gtk.PackType)(1));
			w22.Position = 4;
			w22.Expand = false;
			w22.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 869;
			this.DefaultHeight = 301;
			this.Show ();
			this.button5.Clicked += new global::System.EventHandler (this.DeletePharmacist);
			this.button2.Clicked += new global::System.EventHandler (this.UpdatePharmacist);
		}
	}
}
