
// This file has been generated by the GUI designer. Do not modify.
namespace DatabaseApplication
{
	public partial class AddClientWindow
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Entry hc_entry;
		private global::Gtk.Entry name_entry;
		private global::Gtk.Entry add_entry;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Label label1;
		private global::Gtk.Label label2;
		private global::Gtk.Label label3;
		private global::Gtk.HBox hbox5;
		private global::Gtk.Entry email_entry;
		private global::Gtk.Entry phone_entry;
		private global::Gtk.Calendar dob_calendar;
		private global::Gtk.HBox hbox6;
		private global::Gtk.Label label4;
		private global::Gtk.Label label5;
		private global::Gtk.Label label6;
		private global::Gtk.Button createButon;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DatabaseApplication.AddClientWindow
			this.Name = "DatabaseApplication.AddClientWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Create New Client");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child DatabaseApplication.AddClientWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hc_entry = new global::Gtk.Entry ();
			this.hc_entry.CanFocus = true;
			this.hc_entry.Name = "hc_entry";
			this.hc_entry.IsEditable = true;
			this.hc_entry.InvisibleChar = '●';
			this.hbox1.Add (this.hc_entry);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hc_entry]));
			w1.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.name_entry = new global::Gtk.Entry ();
			this.name_entry.CanFocus = true;
			this.name_entry.Name = "name_entry";
			this.name_entry.IsEditable = true;
			this.name_entry.InvisibleChar = '●';
			this.hbox1.Add (this.name_entry);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.name_entry]));
			w2.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.add_entry = new global::Gtk.Entry ();
			this.add_entry.CanFocus = true;
			this.add_entry.Name = "add_entry";
			this.add_entry.IsEditable = true;
			this.add_entry.InvisibleChar = '●';
			this.hbox1.Add (this.add_entry);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.add_entry]));
			w3.Position = 2;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Healthcard");
			this.hbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label1]));
			w5.Position = 0;
			w5.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Name");
			this.hbox2.Add (this.label2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label2]));
			w6.Position = 1;
			w6.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Address");
			this.hbox2.Add (this.label3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label3]));
			w7.Position = 2;
			w7.Fill = false;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.email_entry = new global::Gtk.Entry ();
			this.email_entry.CanFocus = true;
			this.email_entry.Name = "email_entry";
			this.email_entry.IsEditable = true;
			this.email_entry.InvisibleChar = '●';
			this.hbox5.Add (this.email_entry);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.email_entry]));
			w9.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.phone_entry = new global::Gtk.Entry ();
			this.phone_entry.CanFocus = true;
			this.phone_entry.Name = "phone_entry";
			this.phone_entry.IsEditable = true;
			this.phone_entry.InvisibleChar = '●';
			this.hbox5.Add (this.phone_entry);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.phone_entry]));
			w10.Position = 1;
			// Container child hbox5.Gtk.Box+BoxChild
			this.dob_calendar = new global::Gtk.Calendar ();
			this.dob_calendar.CanFocus = true;
			this.dob_calendar.Name = "dob_calendar";
			this.dob_calendar.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.hbox5.Add (this.dob_calendar);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.dob_calendar]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox1.Add (this.hbox5);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox5]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Email");
			this.hbox6.Add (this.label4);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label4]));
			w13.Position = 0;
			w13.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Phone");
			this.hbox6.Add (this.label5);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label5]));
			w14.Position = 1;
			w14.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Date of birth");
			this.hbox6.Add (this.label6);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label6]));
			w15.Position = 2;
			w15.Fill = false;
			this.vbox1.Add (this.hbox6);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox6]));
			w16.Position = 3;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.createButon = new global::Gtk.Button ();
			this.createButon.WidthRequest = 50;
			this.createButon.CanFocus = true;
			this.createButon.Name = "createButon";
			this.createButon.UseUnderline = true;
			this.createButon.Label = global::Mono.Unix.Catalog.GetString ("Create Client");
			this.vbox1.Add (this.createButon);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.createButon]));
			w17.PackType = ((global::Gtk.PackType)(1));
			w17.Position = 4;
			w17.Expand = false;
			w17.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 529;
			this.DefaultHeight = 301;
			this.Show ();
			this.createButon.Clicked += new global::System.EventHandler (this.CreateClient);
		}
	}
}
