
// This file has been generated by the GUI designer. Do not modify.
namespace DatabaseApplication
{
	public partial class ViewRowWindow
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DatabaseApplication.ViewRowWindow
			this.Name = "DatabaseApplication.ViewRowWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("ViewRowWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
