
// This file has been generated by the GUI designer. Do not modify.
namespace DatabaseApplication
{
	public partial class ViewPrescriptionWindow
	{
		private global::Gtk.VBox vbox4;
		private global::Gtk.HBox hbox20;
		private global::Gtk.Button button9;
		private global::Gtk.Label label24;
		private global::Gtk.HBox hbox14;
		private global::Gtk.Entry pid_entry;
		private global::Gtk.Calendar prescribed_cal;
		private global::Gtk.Calendar expires_cal;
		private global::Gtk.HBox hbox15;
		private global::Gtk.Label label20;
		private global::Gtk.Label label21;
		private global::Gtk.Label label22;
		private global::Gtk.HBox hbox16;
		private global::Gtk.Entry pharm_entry;
		private global::Gtk.Entry client_entry;
		private global::Gtk.HBox hbox17;
		private global::Gtk.Label label25;
		private global::Gtk.Label label26;
		private global::Gtk.HBox hbox18;
		private global::Gtk.Entry name_entry;
		private global::Gtk.Entry dosage_entry;
		private global::Gtk.HBox hbox19;
		private global::Gtk.Label label27;
		private global::Gtk.Label label28;
		private global::Gtk.Entry notes_entry;
		private global::Gtk.Label label29;
		private global::Gtk.Button button11;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DatabaseApplication.ViewPrescriptionWindow
			this.Name = "DatabaseApplication.ViewPrescriptionWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Update Prescription");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child DatabaseApplication.ViewPrescriptionWindow.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox20 = new global::Gtk.HBox ();
			this.hbox20.Name = "hbox20";
			this.hbox20.Spacing = 6;
			// Container child hbox20.Gtk.Box+BoxChild
			this.button9 = new global::Gtk.Button ();
			this.button9.CanFocus = true;
			this.button9.Name = "button9";
			this.button9.UseUnderline = true;
			this.button9.Label = global::Mono.Unix.Catalog.GetString ("Delete Prescription");
			this.hbox20.Add (this.button9);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox20 [this.button9]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox20.Gtk.Box+BoxChild
			this.label24 = new global::Gtk.Label ();
			this.label24.Name = "label24";
			this.label24.LabelProp = global::Mono.Unix.Catalog.GetString (" ");
			this.hbox20.Add (this.label24);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox20 [this.label24]));
			w2.Position = 1;
			w2.Fill = false;
			this.vbox4.Add (this.hbox20);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox20]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox14 = new global::Gtk.HBox ();
			this.hbox14.Name = "hbox14";
			this.hbox14.Spacing = 6;
			// Container child hbox14.Gtk.Box+BoxChild
			this.pid_entry = new global::Gtk.Entry ();
			this.pid_entry.CanFocus = true;
			this.pid_entry.Name = "pid_entry";
			this.pid_entry.IsEditable = true;
			this.pid_entry.InvisibleChar = '●';
			this.hbox14.Add (this.pid_entry);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.pid_entry]));
			w4.Position = 0;
			// Container child hbox14.Gtk.Box+BoxChild
			this.prescribed_cal = new global::Gtk.Calendar ();
			this.prescribed_cal.CanFocus = true;
			this.prescribed_cal.Name = "prescribed_cal";
			this.prescribed_cal.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.hbox14.Add (this.prescribed_cal);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.prescribed_cal]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.expires_cal = new global::Gtk.Calendar ();
			this.expires_cal.CanFocus = true;
			this.expires_cal.Name = "expires_cal";
			this.expires_cal.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.hbox14.Add (this.expires_cal);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.expires_cal]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox4.Add (this.hbox14);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox14]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox15 = new global::Gtk.HBox ();
			this.hbox15.Name = "hbox15";
			this.hbox15.Spacing = 6;
			// Container child hbox15.Gtk.Box+BoxChild
			this.label20 = new global::Gtk.Label ();
			this.label20.Name = "label20";
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString ("Prescription ID");
			this.hbox15.Add (this.label20);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.label20]));
			w8.Position = 0;
			w8.Fill = false;
			// Container child hbox15.Gtk.Box+BoxChild
			this.label21 = new global::Gtk.Label ();
			this.label21.Name = "label21";
			this.label21.LabelProp = global::Mono.Unix.Catalog.GetString ("Prescribed Date");
			this.hbox15.Add (this.label21);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.label21]));
			w9.Position = 1;
			w9.Fill = false;
			// Container child hbox15.Gtk.Box+BoxChild
			this.label22 = new global::Gtk.Label ();
			this.label22.Name = "label22";
			this.label22.LabelProp = global::Mono.Unix.Catalog.GetString ("Expiry Date");
			this.hbox15.Add (this.label22);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.label22]));
			w10.Position = 2;
			w10.Fill = false;
			this.vbox4.Add (this.hbox15);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox15]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox16 = new global::Gtk.HBox ();
			this.hbox16.Name = "hbox16";
			this.hbox16.Spacing = 6;
			// Container child hbox16.Gtk.Box+BoxChild
			this.pharm_entry = new global::Gtk.Entry ();
			this.pharm_entry.CanFocus = true;
			this.pharm_entry.Name = "pharm_entry";
			this.pharm_entry.IsEditable = false;
			this.pharm_entry.InvisibleChar = '●';
			this.hbox16.Add (this.pharm_entry);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox16 [this.pharm_entry]));
			w12.Position = 0;
			// Container child hbox16.Gtk.Box+BoxChild
			this.client_entry = new global::Gtk.Entry ();
			this.client_entry.CanFocus = true;
			this.client_entry.Name = "client_entry";
			this.client_entry.IsEditable = false;
			this.client_entry.InvisibleChar = '●';
			this.hbox16.Add (this.client_entry);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox16 [this.client_entry]));
			w13.Position = 1;
			this.vbox4.Add (this.hbox16);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox16]));
			w14.Position = 3;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox17 = new global::Gtk.HBox ();
			this.hbox17.Name = "hbox17";
			this.hbox17.Spacing = 6;
			// Container child hbox17.Gtk.Box+BoxChild
			this.label25 = new global::Gtk.Label ();
			this.label25.Name = "label25";
			this.label25.LabelProp = global::Mono.Unix.Catalog.GetString ("Pharmacist (SIN)");
			this.hbox17.Add (this.label25);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.label25]));
			w15.Position = 0;
			w15.Fill = false;
			// Container child hbox17.Gtk.Box+BoxChild
			this.label26 = new global::Gtk.Label ();
			this.label26.Name = "label26";
			this.label26.LabelProp = global::Mono.Unix.Catalog.GetString ("Client (Healthcard)");
			this.hbox17.Add (this.label26);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.label26]));
			w16.Position = 1;
			w16.Fill = false;
			this.vbox4.Add (this.hbox17);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox17]));
			w17.Position = 4;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox18 = new global::Gtk.HBox ();
			this.hbox18.Name = "hbox18";
			this.hbox18.Spacing = 6;
			// Container child hbox18.Gtk.Box+BoxChild
			this.name_entry = new global::Gtk.Entry ();
			this.name_entry.CanFocus = true;
			this.name_entry.Name = "name_entry";
			this.name_entry.IsEditable = true;
			this.name_entry.InvisibleChar = '●';
			this.hbox18.Add (this.name_entry);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox18 [this.name_entry]));
			w18.Position = 0;
			// Container child hbox18.Gtk.Box+BoxChild
			this.dosage_entry = new global::Gtk.Entry ();
			this.dosage_entry.CanFocus = true;
			this.dosage_entry.Name = "dosage_entry";
			this.dosage_entry.IsEditable = true;
			this.dosage_entry.InvisibleChar = '●';
			this.hbox18.Add (this.dosage_entry);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox18 [this.dosage_entry]));
			w19.Position = 1;
			this.vbox4.Add (this.hbox18);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox18]));
			w20.Position = 5;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox19 = new global::Gtk.HBox ();
			this.hbox19.Name = "hbox19";
			this.hbox19.Spacing = 6;
			// Container child hbox19.Gtk.Box+BoxChild
			this.label27 = new global::Gtk.Label ();
			this.label27.Name = "label27";
			this.label27.LabelProp = global::Mono.Unix.Catalog.GetString ("Medicine Name");
			this.hbox19.Add (this.label27);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.label27]));
			w21.Position = 0;
			w21.Fill = false;
			// Container child hbox19.Gtk.Box+BoxChild
			this.label28 = new global::Gtk.Label ();
			this.label28.Name = "label28";
			this.label28.LabelProp = global::Mono.Unix.Catalog.GetString ("Medicine Dosage");
			this.hbox19.Add (this.label28);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.label28]));
			w22.Position = 1;
			w22.Fill = false;
			this.vbox4.Add (this.hbox19);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox19]));
			w23.Position = 6;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.notes_entry = new global::Gtk.Entry ();
			this.notes_entry.HeightRequest = 100;
			this.notes_entry.CanFocus = true;
			this.notes_entry.Name = "notes_entry";
			this.notes_entry.IsEditable = true;
			this.notes_entry.InvisibleChar = '●';
			this.vbox4.Add (this.notes_entry);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.notes_entry]));
			w24.Position = 7;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label29 = new global::Gtk.Label ();
			this.label29.Name = "label29";
			this.label29.LabelProp = global::Mono.Unix.Catalog.GetString ("Instructions");
			this.vbox4.Add (this.label29);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label29]));
			w25.Position = 8;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.button11 = new global::Gtk.Button ();
			this.button11.CanFocus = true;
			this.button11.Name = "button11";
			this.button11.UseUnderline = true;
			this.button11.Label = global::Mono.Unix.Catalog.GetString ("Update Prescription");
			this.vbox4.Add (this.button11);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.button11]));
			w26.Position = 9;
			w26.Expand = false;
			w26.Fill = false;
			this.Add (this.vbox4);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 548;
			this.DefaultHeight = 525;
			this.Show ();
			this.button9.Clicked += new global::System.EventHandler (this.DeletePrescription);
			this.button11.Clicked += new global::System.EventHandler (this.UpdatePrescription);
		}
	}
}
