
// This file has been generated by the GUI designer. Do not modify.
namespace DatabaseApplication
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action FileAction;
		private global::Gtk.Action OpenAction;
		private global::Gtk.Action CloseAction;
		private global::Gtk.Action ExitAction;
		private global::Gtk.Action ClientAction;
		private global::Gtk.Action PharmacistsAction;
		private global::Gtk.Action MedicationAction;
		private global::Gtk.Action PrescriptionsAction;
		private global::Gtk.Action CreateNewClientAction;
		private global::Gtk.Action CreateNewPharmacistAction;
		private global::Gtk.Action AddNewMedicationAction;
		private global::Gtk.Action CreateNewPrescriptionAction;
		private global::Gtk.VBox vbox1;
		private global::Gtk.MenuBar menubar1;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Entry SearchBar;
		private global::Gtk.Button SearchBarButton;
		private global::Gtk.VBox vbox2;
		private global::Gtk.HBox hbox1;
		private global::Gtk.HBox hbox4;
		private global::Gtk.HBox hbox6;
		private global::Gtk.Button clientButton;
		private global::Gtk.Button pharmButton;
		private global::Gtk.HBox hbox5;
		private global::Gtk.Button medicationButton;
		private global::Gtk.Button prescriptionButton;
		private global::Gtk.Image image1;
		private global::Gtk.ScrolledWindow scrolledwindow1;
		private global::Gtk.TreeView ListView;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DatabaseApplication.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("_File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_File");
			w1.Add (this.FileAction, "<Alt>f");
			this.OpenAction = new global::Gtk.Action ("OpenAction", global::Mono.Unix.Catalog.GetString ("_Open"), null, null);
			this.OpenAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Open");
			w1.Add (this.OpenAction, "<Primary>o");
			this.CloseAction = new global::Gtk.Action ("CloseAction", global::Mono.Unix.Catalog.GetString ("C_lose"), null, null);
			this.CloseAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("C_lose");
			w1.Add (this.CloseAction, "<Primary>c");
			this.ExitAction = new global::Gtk.Action ("ExitAction", global::Mono.Unix.Catalog.GetString ("E_xit"), null, null);
			this.ExitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("E_xit");
			w1.Add (this.ExitAction, "<Primary>x");
			this.ClientAction = new global::Gtk.Action ("ClientAction", global::Mono.Unix.Catalog.GetString ("Client"), null, null);
			this.ClientAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Client");
			w1.Add (this.ClientAction, null);
			this.PharmacistsAction = new global::Gtk.Action ("PharmacistsAction", global::Mono.Unix.Catalog.GetString ("Pharmacists"), null, null);
			this.PharmacistsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Pharmacists");
			w1.Add (this.PharmacistsAction, null);
			this.MedicationAction = new global::Gtk.Action ("MedicationAction", global::Mono.Unix.Catalog.GetString ("Medication"), null, null);
			this.MedicationAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Medication");
			w1.Add (this.MedicationAction, null);
			this.PrescriptionsAction = new global::Gtk.Action ("PrescriptionsAction", global::Mono.Unix.Catalog.GetString ("Prescriptions"), null, null);
			this.PrescriptionsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Prescriptions");
			w1.Add (this.PrescriptionsAction, null);
			this.CreateNewClientAction = new global::Gtk.Action ("CreateNewClientAction", global::Mono.Unix.Catalog.GetString ("Create New Client"), null, null);
			this.CreateNewClientAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Create New Client");
			w1.Add (this.CreateNewClientAction, null);
			this.CreateNewPharmacistAction = new global::Gtk.Action ("CreateNewPharmacistAction", global::Mono.Unix.Catalog.GetString ("Create New Pharmacist"), null, null);
			this.CreateNewPharmacistAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Create New Pharmacist");
			w1.Add (this.CreateNewPharmacistAction, null);
			this.AddNewMedicationAction = new global::Gtk.Action ("AddNewMedicationAction", global::Mono.Unix.Catalog.GetString ("Add New Medication"), null, null);
			this.AddNewMedicationAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Add New Medication");
			w1.Add (this.AddNewMedicationAction, null);
			this.CreateNewPrescriptionAction = new global::Gtk.Action ("CreateNewPrescriptionAction", global::Mono.Unix.Catalog.GetString ("Create New Prescription"), null, null);
			this.CreateNewPrescriptionAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Create New Prescription");
			w1.Add (this.CreateNewPrescriptionAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "DatabaseApplication.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("PharmaHodge");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child DatabaseApplication.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.HeightRequest = 100;
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='ClientAction' action='ClientAction'><menuitem name='CreateNewClientAction' action='CreateNewClientAction'/></menu><menu name='PharmacistsAction' action='PharmacistsAction'><menuitem name='CreateNewPharmacistAction' action='CreateNewPharmacistAction'/></menu><menu name='MedicationAction' action='MedicationAction'><menuitem name='AddNewMedicationAction' action='AddNewMedicationAction'/></menu><menu name='PrescriptionsAction' action='PrescriptionsAction'><menuitem name='CreateNewPrescriptionAction' action='CreateNewPrescriptionAction'/></menu></menubar></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox1.Add (this.menubar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.WidthRequest = 50;
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.SearchBar = new global::Gtk.Entry ();
			this.SearchBar.CanFocus = true;
			this.SearchBar.Name = "SearchBar";
			this.SearchBar.IsEditable = true;
			this.SearchBar.InvisibleChar = '●';
			this.hbox2.Add (this.SearchBar);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.SearchBar]));
			w3.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.SearchBarButton = new global::Gtk.Button ();
			this.SearchBarButton.WidthRequest = 50;
			this.SearchBarButton.CanFocus = true;
			this.SearchBarButton.Name = "SearchBarButton";
			this.SearchBarButton.UseUnderline = true;
			this.SearchBarButton.Label = global::Mono.Unix.Catalog.GetString ("Search");
			this.hbox2.Add (this.SearchBarButton);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.SearchBarButton]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.HeightRequest = 100;
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.HeightRequest = 100;
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.clientButton = new global::Gtk.Button ();
			this.clientButton.WidthRequest = 100;
			this.clientButton.HeightRequest = 99;
			this.clientButton.CanFocus = true;
			this.clientButton.Name = "clientButton";
			this.clientButton.UseUnderline = true;
			this.clientButton.Label = global::Mono.Unix.Catalog.GetString ("Clients");
			this.hbox6.Add (this.clientButton);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.clientButton]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.pharmButton = new global::Gtk.Button ();
			this.pharmButton.WidthRequest = 100;
			this.pharmButton.HeightRequest = 100;
			this.pharmButton.CanFocus = true;
			this.pharmButton.Name = "pharmButton";
			this.pharmButton.UseUnderline = true;
			this.pharmButton.Label = global::Mono.Unix.Catalog.GetString ("Pharmacists");
			this.hbox6.Add (this.pharmButton);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.pharmButton]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.hbox4.Add (this.hbox6);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.hbox6]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.HeightRequest = 100;
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.medicationButton = new global::Gtk.Button ();
			this.medicationButton.WidthRequest = 100;
			this.medicationButton.HeightRequest = 100;
			this.medicationButton.CanFocus = true;
			this.medicationButton.Name = "medicationButton";
			this.medicationButton.UseUnderline = true;
			this.medicationButton.Label = global::Mono.Unix.Catalog.GetString ("Medication");
			this.hbox5.Add (this.medicationButton);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.medicationButton]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.prescriptionButton = new global::Gtk.Button ();
			this.prescriptionButton.WidthRequest = 99;
			this.prescriptionButton.HeightRequest = 100;
			this.prescriptionButton.CanFocus = true;
			this.prescriptionButton.Name = "prescriptionButton";
			this.prescriptionButton.UseUnderline = true;
			this.prescriptionButton.Label = global::Mono.Unix.Catalog.GetString ("Prescriptions");
			this.hbox5.Add (this.prescriptionButton);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.prescriptionButton]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			this.hbox4.Add (this.hbox5);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.hbox5]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			this.hbox1.Add (this.hbox4);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hbox4]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.image1 = new global::Gtk.Image ();
			this.image1.WidthRequest = 100;
			this.image1.HeightRequest = 100;
			this.image1.Name = "image1";
			this.image1.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./rx.png"));
			this.hbox1.Add (this.image1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.image1]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			this.ListView = new global::Gtk.TreeView ();
			this.ListView.CanFocus = true;
			this.ListView.Name = "ListView";
			this.scrolledwindow1.Add (this.ListView);
			this.vbox2.Add (this.scrolledwindow1);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.scrolledwindow1]));
			w16.Position = 1;
			this.vbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox2]));
			w17.Position = 2;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 623;
			this.DefaultHeight = 600;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.OpenAction.Activated += new global::System.EventHandler (this.OnOpen);
			this.CloseAction.Activated += new global::System.EventHandler (this.OnClose);
			this.ExitAction.Activated += new global::System.EventHandler (this.OnExit);
			this.CreateNewClientAction.Activated += new global::System.EventHandler (this.newClient);
			this.CreateNewPharmacistAction.Activated += new global::System.EventHandler (this.newPharm);
			this.AddNewMedicationAction.Activated += new global::System.EventHandler (this.newMed);
			this.CreateNewPrescriptionAction.Activated += new global::System.EventHandler (this.newPres);
			this.SearchBarButton.Clicked += new global::System.EventHandler (this.SearchTree);
			this.clientButton.Entered += new global::System.EventHandler (this.ClientClick);
			this.pharmButton.Entered += new global::System.EventHandler (this.PharmClick);
			this.medicationButton.Entered += new global::System.EventHandler (this.MedClick);
			this.prescriptionButton.Entered += new global::System.EventHandler (this.PrescripClick);
			this.ListView.RowActivated += new global::Gtk.RowActivatedHandler (this.ViewRow);
		}
	}
}
