
// This file has been generated by the GUI designer. Do not modify.
namespace DatabaseApplication
{
	public partial class AddMedicineWindow
	{
		private global::Gtk.VBox vbox3;
		private global::Gtk.HBox hbox11;
		private global::Gtk.Entry name_entry;
		private global::Gtk.Entry class_entry;
		private global::Gtk.HBox hbox12;
		private global::Gtk.Label name;
		private global::Gtk.Label label18;
		private global::Gtk.HBox hbox13;
		private global::Gtk.Entry dosage_entry;
		private global::Gtk.Entry type_entry;
		private global::Gtk.HBox hbox14;
		private global::Gtk.Label label19;
		private global::Gtk.Label label17;
		private global::Gtk.Label label21;
		private global::Gtk.Button button3;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DatabaseApplication.AddMedicineWindow
			this.Name = "DatabaseApplication.AddMedicineWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Add Medicine");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child DatabaseApplication.AddMedicineWindow.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox ();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.name_entry = new global::Gtk.Entry ();
			this.name_entry.CanFocus = true;
			this.name_entry.Name = "name_entry";
			this.name_entry.IsEditable = true;
			this.name_entry.InvisibleChar = '●';
			this.hbox11.Add (this.name_entry);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.name_entry]));
			w1.Position = 0;
			// Container child hbox11.Gtk.Box+BoxChild
			this.class_entry = new global::Gtk.Entry ();
			this.class_entry.CanFocus = true;
			this.class_entry.Name = "class_entry";
			this.class_entry.IsEditable = true;
			this.class_entry.InvisibleChar = '●';
			this.hbox11.Add (this.class_entry);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.class_entry]));
			w2.Position = 2;
			this.vbox3.Add (this.hbox11);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox11]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox ();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.name = new global::Gtk.Label ();
			this.name.Name = "name";
			this.name.LabelProp = global::Mono.Unix.Catalog.GetString ("Name");
			this.hbox12.Add (this.name);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.name]));
			w4.Position = 0;
			// Container child hbox12.Gtk.Box+BoxChild
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Classification");
			this.hbox12.Add (this.label18);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.label18]));
			w5.Position = 1;
			this.vbox3.Add (this.hbox12);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox12]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox13 = new global::Gtk.HBox ();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.dosage_entry = new global::Gtk.Entry ();
			this.dosage_entry.CanFocus = true;
			this.dosage_entry.Name = "dosage_entry";
			this.dosage_entry.IsEditable = true;
			this.dosage_entry.InvisibleChar = '●';
			this.hbox13.Add (this.dosage_entry);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.dosage_entry]));
			w7.Position = 0;
			// Container child hbox13.Gtk.Box+BoxChild
			this.type_entry = new global::Gtk.Entry ();
			this.type_entry.CanFocus = true;
			this.type_entry.Name = "type_entry";
			this.type_entry.IsEditable = true;
			this.type_entry.InvisibleChar = '●';
			this.hbox13.Add (this.type_entry);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.type_entry]));
			w8.Position = 2;
			this.vbox3.Add (this.hbox13);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox13]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox14 = new global::Gtk.HBox ();
			this.hbox14.Name = "hbox14";
			this.hbox14.Spacing = 6;
			// Container child hbox14.Gtk.Box+BoxChild
			this.label19 = new global::Gtk.Label ();
			this.label19.Name = "label19";
			this.hbox14.Add (this.label19);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.label19]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("Dosage");
			this.hbox14.Add (this.label17);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.label17]));
			w11.Position = 1;
			// Container child hbox14.Gtk.Box+BoxChild
			this.label21 = new global::Gtk.Label ();
			this.label21.Name = "label21";
			this.label21.LabelProp = global::Mono.Unix.Catalog.GetString ("Type");
			this.hbox14.Add (this.label21);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.label21]));
			w12.Position = 2;
			this.vbox3.Add (this.hbox14);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox14]));
			w13.Position = 3;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.button3 = new global::Gtk.Button ();
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.Label = global::Mono.Unix.Catalog.GetString ("Create Medicine");
			this.vbox3.Add (this.button3);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.button3]));
			w14.PackType = ((global::Gtk.PackType)(1));
			w14.Position = 4;
			w14.Expand = false;
			w14.Fill = false;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 510;
			this.DefaultHeight = 300;
			this.Show ();
			this.button3.Clicked += new global::System.EventHandler (this.CreateMedicine);
		}
	}
}
