
// This file has been generated by the GUI designer. Do not modify.
namespace DatabaseApplication
{
	public partial class ViewClientWindow
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Entry hc_entry;
		private global::Gtk.Entry name_entry;
		private global::Gtk.Entry address_entry;
		private global::Gtk.Button button8;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Label label1;
		private global::Gtk.Label label2;
		private global::Gtk.Label label3;
		private global::Gtk.Label label19;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Entry email_entry;
		private global::Gtk.Entry phone_entry;
		private global::Gtk.Calendar dob_cal;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Label label4;
		private global::Gtk.Label label5;
		private global::Gtk.Label label6;
		private global::Gtk.Button button1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DatabaseApplication.ViewClientWindow
			this.Name = "DatabaseApplication.ViewClientWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Update Client");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child DatabaseApplication.ViewClientWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hc_entry = new global::Gtk.Entry ();
			this.hc_entry.Name = "hc_entry";
			this.hc_entry.IsEditable = false;
			this.hc_entry.InvisibleChar = '●';
			this.hbox1.Add (this.hc_entry);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hc_entry]));
			w1.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.name_entry = new global::Gtk.Entry ();
			this.name_entry.CanFocus = true;
			this.name_entry.Name = "name_entry";
			this.name_entry.IsEditable = true;
			this.name_entry.InvisibleChar = '●';
			this.hbox1.Add (this.name_entry);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.name_entry]));
			w2.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.address_entry = new global::Gtk.Entry ();
			this.address_entry.CanFocus = true;
			this.address_entry.Name = "address_entry";
			this.address_entry.IsEditable = true;
			this.address_entry.InvisibleChar = '●';
			this.hbox1.Add (this.address_entry);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.address_entry]));
			w3.Position = 2;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button8 = new global::Gtk.Button ();
			this.button8.CanFocus = true;
			this.button8.Name = "button8";
			this.button8.UseUnderline = true;
			this.button8.Label = global::Mono.Unix.Catalog.GetString ("Delete Client");
			this.hbox1.Add (this.button8);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button8]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Healthcard");
			this.hbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label1]));
			w6.Position = 0;
			w6.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Name");
			this.hbox2.Add (this.label2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label2]));
			w7.Position = 1;
			w7.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Address");
			this.hbox2.Add (this.label3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label3]));
			w8.Position = 2;
			w8.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label19 = new global::Gtk.Label ();
			this.label19.Name = "label19";
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString (" ");
			this.hbox2.Add (this.label19);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label19]));
			w9.Position = 3;
			w9.Fill = false;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.email_entry = new global::Gtk.Entry ();
			this.email_entry.CanFocus = true;
			this.email_entry.Name = "email_entry";
			this.email_entry.IsEditable = true;
			this.email_entry.InvisibleChar = '●';
			this.hbox3.Add (this.email_entry);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.email_entry]));
			w11.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.phone_entry = new global::Gtk.Entry ();
			this.phone_entry.CanFocus = true;
			this.phone_entry.Name = "phone_entry";
			this.phone_entry.IsEditable = true;
			this.phone_entry.InvisibleChar = '●';
			this.hbox3.Add (this.phone_entry);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.phone_entry]));
			w12.Position = 1;
			// Container child hbox3.Gtk.Box+BoxChild
			this.dob_cal = new global::Gtk.Calendar ();
			this.dob_cal.CanFocus = true;
			this.dob_cal.Name = "dob_cal";
			this.dob_cal.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.hbox3.Add (this.dob_cal);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.dob_cal]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Email");
			this.hbox4.Add (this.label4);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label4]));
			w15.Position = 0;
			w15.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Phone");
			this.hbox4.Add (this.label5);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label5]));
			w16.Position = 1;
			w16.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Date of birth");
			this.hbox4.Add (this.label6);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label6]));
			w17.Position = 2;
			w17.Fill = false;
			this.vbox1.Add (this.hbox4);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox4]));
			w18.Position = 3;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.button1 = new global::Gtk.Button ();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString ("Update Client");
			this.vbox1.Add (this.button1);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.button1]));
			w19.Position = 4;
			w19.Expand = false;
			w19.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 598;
			this.DefaultHeight = 301;
			this.Show ();
			this.button8.Clicked += new global::System.EventHandler (this.DeleteClient);
			this.button1.Clicked += new global::System.EventHandler (this.UpdateClient);
		}
	}
}
