
// This file has been generated by the GUI designer. Do not modify.
namespace DatabaseApplication
{
	public partial class ViewMedicineWindow
	{
		private global::Gtk.VBox vbox3;
		private global::Gtk.HBox hbox8;
		private global::Gtk.Entry name_entry;
		private global::Gtk.Entry class_entry;
		private global::Gtk.HBox hbox9;
		private global::Gtk.Label label15;
		private global::Gtk.Label label16;
		private global::Gtk.HBox hbox10;
		private global::Gtk.Entry dosage_entry;
		private global::Gtk.Entry type_entry;
		private global::Gtk.HBox hbox11;
		private global::Gtk.Label label17;
		private global::Gtk.Label label18;
		private global::Gtk.HSeparator hseparator1;
		private global::Gtk.HBox hbox13;
		private global::Gtk.Button button7;
		private global::Gtk.HSeparator hseparator2;
		private global::Gtk.Button button3;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DatabaseApplication.ViewMedicineWindow
			this.Name = "DatabaseApplication.ViewMedicineWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Update Medication");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child DatabaseApplication.ViewMedicineWindow.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.name_entry = new global::Gtk.Entry ();
			this.name_entry.CanFocus = true;
			this.name_entry.Name = "name_entry";
			this.name_entry.IsEditable = false;
			this.name_entry.InvisibleChar = '●';
			this.hbox8.Add (this.name_entry);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.name_entry]));
			w1.Position = 0;
			// Container child hbox8.Gtk.Box+BoxChild
			this.class_entry = new global::Gtk.Entry ();
			this.class_entry.CanFocus = true;
			this.class_entry.Name = "class_entry";
			this.class_entry.IsEditable = true;
			this.class_entry.InvisibleChar = '●';
			this.hbox8.Add (this.class_entry);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.class_entry]));
			w2.Position = 2;
			this.vbox3.Add (this.hbox8);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox8]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Name");
			this.hbox9.Add (this.label15);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.label15]));
			w4.Position = 0;
			w4.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Classification");
			this.hbox9.Add (this.label16);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.label16]));
			w5.Position = 2;
			w5.Fill = false;
			this.vbox3.Add (this.hbox9);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox9]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.dosage_entry = new global::Gtk.Entry ();
			this.dosage_entry.CanFocus = true;
			this.dosage_entry.Name = "dosage_entry";
			this.dosage_entry.IsEditable = false;
			this.dosage_entry.InvisibleChar = '●';
			this.hbox10.Add (this.dosage_entry);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.dosage_entry]));
			w7.Position = 0;
			// Container child hbox10.Gtk.Box+BoxChild
			this.type_entry = new global::Gtk.Entry ();
			this.type_entry.CanFocus = true;
			this.type_entry.Name = "type_entry";
			this.type_entry.IsEditable = true;
			this.type_entry.InvisibleChar = '●';
			this.hbox10.Add (this.type_entry);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.type_entry]));
			w8.Position = 2;
			this.vbox3.Add (this.hbox10);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox10]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox ();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("Dosage");
			this.hbox11.Add (this.label17);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.label17]));
			w10.Position = 0;
			w10.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Type");
			this.hbox11.Add (this.label18);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.label18]));
			w11.Position = 2;
			w11.Fill = false;
			this.vbox3.Add (this.hbox11);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox11]));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox3.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hseparator1]));
			w13.Position = 4;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox13 = new global::Gtk.HBox ();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.button7 = new global::Gtk.Button ();
			this.button7.CanFocus = true;
			this.button7.Name = "button7";
			this.button7.UseUnderline = true;
			this.button7.Label = global::Mono.Unix.Catalog.GetString ("Delete Medication");
			this.hbox13.Add (this.button7);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.button7]));
			w14.Position = 1;
			w14.Fill = false;
			this.vbox3.Add (this.hbox13);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox13]));
			w15.Position = 5;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.Name = "hseparator2";
			this.vbox3.Add (this.hseparator2);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hseparator2]));
			w16.Position = 6;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.button3 = new global::Gtk.Button ();
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.Label = global::Mono.Unix.Catalog.GetString ("Update Medication");
			this.vbox3.Add (this.button3);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.button3]));
			w17.PackType = ((global::Gtk.PackType)(1));
			w17.Position = 7;
			w17.Expand = false;
			w17.Fill = false;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 506;
			this.DefaultHeight = 314;
			this.Show ();
			this.button7.Clicked += new global::System.EventHandler (this.DeleteMedication);
			this.button3.Clicked += new global::System.EventHandler (this.UpdateMedication);
		}
	}
}
